# Changes here will be overwritten by Copier
_commit: 1a45ad8
_src_path: gh:audivir/copier-template
description: Terminal UI for finding and removing duplicate images and videos, and sorting media, built on czkawka_core.
github_org: audivir
project_name: image_dedup
project_slug: image_dedup
project_type: rust
publishable: false
